image: maven:latest

stages:
- init
- deploy

init:
  stage: init

  script:
  - 'mvn clean package'

  only:
  - master

deploy_production:

  stage: deploy

  script:
      - 'git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/taxihub-backend.git'
      - 'git push heroku master'

  only:
    - master
